### ISSUE TITLE
question: how to specify the proxy settings?

### ISSUE THREAD

**Issue by eriviere** [peteward44/gulp-artifactory-upload#7]
Does the plugin can use the env variable HTTP_PROXY on linux?
If not which option are you using to set the proxy host and port?

**Comment by peteward44** [comment]
It uses the 'request' npm package which apparently does respect the HTTP_PROXY and HTTPS_PROXY env vars (see https://github.com/request/request)

I have no way of testing this myself but reading the request docs it would seem it should just work without any modifications
